# Generated by Django 5.1.1 on 2024-10-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='resume',
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(default='<django.db.models.fields.CharField>@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(default='<django.db.models.fields.CharField>.com', max_length=255),
        ),
    ]
