# Generated by Django 5.1.1 on 2024-12-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_company_logo_remove_student_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/companies/'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='<django.db.models.fields.CharField>@gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/students/'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(max_length=255),
        ),
    ]
