# Generated by Django 5.0.1 on 2024-12-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTestData',
            fields=[
                ('testId', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('questions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentTestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testNumber', models.IntegerField()),
                ('score', models.IntegerField()),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_count', models.IntegerField(default=0)),
                ('last_test_score', models.IntegerField(default=0)),
                ('mathematics_score', models.IntegerField(default=0)),
                ('machine_learning_score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subjecttestdata')),
            ],
        ),
    ]
