# Generated by Django 5.0.1 on 2024-12-02 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_subjecttestdata_studenttestresults_studenttestdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttestdata',
            name='testDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='StudentTestResults',
        ),
    ]
