# Generated by Django 5.1.1 on 2024-12-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_subjecttestdata_testdate_delete_studenttestresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='student_applied',
            field=models.JSONField(default=dict),
        ),
    ]
